exclude: '^docs/conf.py'

repos:
-   repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
        - types-freezegun
        - types-python-dateutil
        - types-pkg_resources
        - types-PyYAML
        - types-tabulate
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    - id: add-trailing-comma
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    - id: reorder-python-imports
      args: [--application-directories=.:src]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: debug-statements
- repo: https://github.com/hadialqattan/pycln
  rev: v1.0.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]
