exclude: '^docs/conf.py'

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    - id: add-trailing-comma
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    - id: reorder-python-imports
